// <auto-generated />
using System;
using AE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AE.Data.Migrations
{
    [DbContext(typeof(AECCodeChallangeContext))]
    partial class AECCodeChallangeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AE.Data.Entities.Port", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Lattitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longtitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Port");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66ae4d81-1618-4441-aae6-b6b18e4b0ad8"),
                            Lattitude = 0.14630046938311025,
                            Longtitude = 0.11497967317744084,
                            Name = "Port1"
                        },
                        new
                        {
                            Id = new Guid("de6216d8-3a76-4f5e-a42b-e8bd08ac92f2"),
                            Lattitude = 0.76874053823909283,
                            Longtitude = 0.71997172749215044,
                            Name = "Port2"
                        },
                        new
                        {
                            Id = new Guid("f00193f9-6e46-46a3-98f6-93c1201ec5fb"),
                            Lattitude = 0.81143095164558876,
                            Longtitude = 0.93144283498242786,
                            Name = "Port3"
                        },
                        new
                        {
                            Id = new Guid("e5f14f2e-05d6-43a4-9b06-952bb72e77b4"),
                            Lattitude = 0.23939563214423232,
                            Longtitude = 0.60906417047873662,
                            Name = "Port4"
                        },
                        new
                        {
                            Id = new Guid("ac521789-c21e-4a6a-ad4b-3f23190f14c7"),
                            Lattitude = 0.21883279124681088,
                            Longtitude = 0.30178627922734125,
                            Name = "Port5"
                        });
                });

            modelBuilder.Entity("AE.Data.Entities.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longtitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("text");

                    b.Property<double>("Velocity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Ship");
                });
#pragma warning restore 612, 618
        }
    }
}
